import type { AuditLog } from "@/types/auditLog"

const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    userId: "u1",
    userName: "John Admin",
    userEmail: "john@example.com",
    action: "CREATE",
    entity: "Agent",
    entityId: "a1",
    entityName: "Tech Solutions Inc",
    description: "Created new agent account",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    userId: "u2",
    userName: "Sarah Manager",
    userEmail: "sarah@example.com",
    action: "UPDATE",
    entity: "Discount",
    entityId: "d1",
    entityName: "SUMMER2024",
    description: "Updated discount percentage from 10% to 15%",
    changes: [
      { field: "discountPercentage", oldValue: 10, newValue: 15 },
    ],
    ipAddress: "192.168.1.105",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    userId: "u3",
    userName: "Mike User",
    userEmail: "mike@example.com",
    action: "VIEW",
    entity: "Agent",
    entityId: "a1",
    entityName: "Tech Solutions Inc",
    description: "Viewed agent details",
    ipAddress: "192.168.1.110",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    userId: "u1",
    userName: "John Admin",
    userEmail: "john@example.com",
    action: "DELETE",
    entity: "Branch",
    entityId: "b2",
    entityName: "Downtown Branch",
    description: "Deleted branch",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    userId: "u4",
    userName: "Lisa Analyst",
    userEmail: "lisa@example.com",
    action: "EXPORT",
    entity: "Transaction",
    entityId: "t1",
    entityName: "Transaction Report",
    description: "Exported transaction data to CSV",
    ipAddress: "192.168.1.115",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    userId: "u2",
    userName: "Sarah Manager",
    userEmail: "sarah@example.com",
    action: "CREATE",
    entity: "Discount",
    entityId: "d2",
    entityName: "FALL2024",
    description: "Created new discount offer",
    ipAddress: "192.168.1.105",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "7",
    userId: "u5",
    userName: "Robert Operator",
    userEmail: "robert@example.com",
    action: "LOGIN",
    entity: "User",
    entityId: "u5",
    entityName: "Robert Operator",
    description: "User logged in",
    ipAddress: "192.168.1.120",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "8",
    userId: "u3",
    userName: "Mike User",
    userEmail: "mike@example.com",
    action: "UPDATE",
    entity: "Agent",
    entityId: "a3",
    entityName: "Global Services Ltd",
    description: "Updated agent contact information",
    changes: [
      { field: "contactNumber", oldValue: "555-0100", newValue: "555-0101" },
    ],
    ipAddress: "192.168.1.110",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "9",
    userId: "u1",
    userName: "John Admin",
    userEmail: "john@example.com",
    action: "DELETE",
    entity: "Discount",
    entityId: "d3",
    entityName: "OLDOFFER",
    description: "Deleted expired discount",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "10",
    userId: "u4",
    userName: "Lisa Analyst",
    userEmail: "lisa@example.com",
    action: "IMPORT",
    entity: "Transaction",
    entityId: "t2",
    entityName: "Bulk Transactions",
    description: "Imported transactions from file",
    ipAddress: "192.168.1.115",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    status: "Success",
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
]

export { mockAuditLogs }
